<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';
require __DIR__.'/payment_demo.php';

$action=$_GET['action']??'';
function registry():array{static $g=null;if($g!==null)return $g;$g=json_decode((string)file_get_contents(__DIR__.'/../config/games.json'),true);return is_array($g)?$g:[];}
function valid_game(string $c):bool{foreach(registry() as $g)if(($g['code']??'')===$c)return true;return false;}
function game_cfg(string $c):array{foreach(registry() as $g)if(($g['code']??'')===$c){$s=db()->prepare('SELECT enabled,min_bet,max_bet,round_seconds,difficulty FROM game_admin_config WHERE game_code=?');$s->execute([$c]);$x=$s->fetch();if($x){$g['enabled']=(bool)$x['enabled'];$g['min_bet']=(float)$x['min_bet'];$g['max_bet']=(float)$x['max_bet'];$g['round_seconds']=(int)$x['round_seconds'];$g['difficulty']=$x['difficulty'];}return $g;}json_out(['error'=>'unknown_game'],404);}
function ensure_auth_tables():void{db()->exec("CREATE TABLE IF NOT EXISTS admin_login_attempts(username VARCHAR(80) PRIMARY KEY, failures INT NOT NULL DEFAULT 0, locked_until TIMESTAMPTZ)");}
function login_locked(string $u):bool{$s=db()->prepare('SELECT locked_until FROM admin_login_attempts WHERE username=?');$s->execute([$u]);$v=$s->fetchColumn();return $v&&strtotime((string)$v)>time();}
function login_fail(string $u):void{$s=db()->prepare("INSERT INTO admin_login_attempts(username,failures,locked_until) VALUES(?,1,now()+interval '1 minute') ON CONFLICT(username) DO UPDATE SET failures=admin_login_attempts.failures+1,locked_until=CASE WHEN admin_login_attempts.failures+1>=5 THEN now()+interval '15 minutes' ELSE admin_login_attempts.locked_until END");$s->execute([$u]);}
function login_reset(string $u):void{$s=db()->prepare('DELETE FROM admin_login_attempts WHERE username=?');$s->execute([$u]);}
function issue_player_session(int $id):void{start_session('__Host-ha88_player');session_regenerate_id(true);$_SESSION['player']=['id'=>$id];$_SESSION['login_at']=time();$_SESSION['last_seen']=time();}
function wallet_balance(int $pid):float{$s=db()->prepare('SELECT balance FROM player_wallets WHERE player_id=?');$s->execute([$pid]);$v=$s->fetchColumn();return $v===false?0.0:(float)$v;}
function ledger(int $pid,float $delta,string $type,string $ref,?string $reason=null):float{
 $pdo=db();$pdo->beginTransaction();try{$s=$pdo->prepare('SELECT balance FROM player_wallets WHERE player_id=? FOR UPDATE');$s->execute([$pid]);$b=$s->fetchColumn();if($b===false)throw new RuntimeException('wallet_missing');$new=(float)$b+$delta;if($new<-0.00001)throw new RuntimeException('insufficient_balance');$u=$pdo->prepare('UPDATE player_wallets SET balance=?,version=version+1,updated_at=now() WHERE player_id=?');$u->execute([$new,$pid]);$l=$pdo->prepare('INSERT INTO wallet_ledger(player_id,amount,balance_after,type,reference_id,reason) VALUES(?,?,?,?,?,?)');$l->execute([$pid,$delta,$new,$type,$ref,$reason]);$pdo->commit();return $new;}catch(Throwable $e){$pdo->rollBack();throw $e;}}
function new_round(string $game):array{$c=game_cfg($game);if(empty($c['enabled']))json_out(['error'=>'game_disabled'],409);$rid=gmdate('YmdHis').'-'.bin2hex(random_bytes(6));$s=db()->prepare('INSERT INTO game_rounds(game_code,round_id,status,closes_at) VALUES(?,? ,\'open\',now()+make_interval(secs=>?)) RETURNING round_id,opened_at,closes_at');$s->execute([$game,$rid,max(5,(int)$c['round_seconds'])]);return $s->fetch();}
function settle_round(string $game,string $rid):array{
 $pdo=db();$pdo->beginTransaction();try{$s=$pdo->prepare('SELECT * FROM game_rounds WHERE game_code=? AND round_id=? FOR UPDATE');$s->execute([$game,$rid]);$r=$s->fetch();if(!$r)throw new RuntimeException('round_not_found');if($r['status']==='settled'){$pdo->commit();return $r;}
 $q=$pdo->prepare('SELECT result_code FROM game_test_round_controls WHERE game_code=? AND round_id=?');$q->execute([$game,$rid]);$result=$q->fetchColumn();if(!$result){$pool=['A','B','C','D'];$result=$pool[random_int(0,count($pool)-1)];}
 $b=$pdo->prepare("SELECT * FROM bets WHERE round_id=? AND status='pending' FOR UPDATE");$b->execute([$rid]);$bets=$b->fetchAll();
 foreach($bets as $bet){$won=((string)$bet['bet_code']===(string)$result);$payout=$won?(float)$bet['amount']*2:0.0;$status=$won?'won':'lost';if($payout>0){$ws=$pdo->prepare('SELECT balance FROM player_wallets WHERE player_id=? FOR UPDATE');$ws->execute([(int)$bet['player_id']]);$bal=(float)$ws->fetchColumn();$nb=$bal+$payout;$pdo->prepare('UPDATE player_wallets SET balance=?,version=version+1,updated_at=now() WHERE player_id=?')->execute([$nb,(int)$bet['player_id']]);$pdo->prepare('INSERT INTO wallet_ledger(player_id,amount,balance_after,type,reference_id,reason) VALUES(?,?,?,?,?,?)')->execute([(int)$bet['player_id'],$payout,$nb,'game_payout',(string)$bet['id'],'TEST round settlement']);}
 $pdo->prepare('UPDATE bets SET status=?,payout=?,settled_at=now() WHERE id=?')->execute([$status,$payout,$bet['id']]);}
 $u=$pdo->prepare("UPDATE game_rounds SET status='settled',result_code=?,settled_at=now() WHERE id=? RETURNING *");$u->execute([$result,$r['id']]);$out=$u->fetch();$pdo->commit();return $out;}catch(Throwable $e){$pdo->rollBack();throw $e;}}

try{
 ensure_auth_tables();
 if (payment_routes(db(), admin_session(), player_session(), $action, $_SERVER['REQUEST_METHOD'] ?? 'GET')) { exit; }

 if($action==='health'){json_out(['ok'=>true,'service'=>'HA88Lucky','mode'=>'TEST','time'=>gmdate('c')]);}
 if($action==='admin_csrf'){start_session('__Host-ha88_admin');json_out(['ok'=>true,'csrf'=>csrf_token()]);}
 if($action==='player_csrf'){require_player();json_out(['ok'=>true,'csrf'=>csrf_token()]);}
 if($action==='admin_login'){
  require_post();$b=body();$u=trim((string)($b['username']??''));$pw=(string)($b['password']??'');$otp=trim((string)($b['otp']??''));
  if($u===''||strlen($pw)<8||login_locked($u))json_out(['error'=>'invalid_credentials'],401);
  $s=db()->prepare('SELECT id,username,password_hash,role,totp_secret_enc,active FROM admin_accounts WHERE username=? LIMIT 1');$s->execute([$u]);$r=$s->fetch();$ok=$r&&!empty($r['active'])&&password_verify($pw,(string)$r['password_hash']);
  if(!$ok||empty($r['totp_secret_enc'])||!verify_totp(decrypt_secret((string)$r['totp_secret_enc']),$otp)){login_fail($u);json_out(['error'=>'invalid_credentials'],401);}
  login_reset($u);start_session('__Host-ha88_admin');session_regenerate_id(true);$_SESSION['admin']=['id'=>(int)$r['id'],'username'=>$r['username'],'role'=>$r['role']];$_SESSION['admin_login_at']=time();$_SESSION['admin_idle']=time();$_SESSION['csrf']=bin2hex(random_bytes(32));db()->prepare('UPDATE admin_accounts SET last_login_at=now() WHERE id=?')->execute([(int)$r['id']]);audit((int)$r['id'],'ADMIN_LOGIN','AUTH',$r['username']);json_out(['ok'=>true,'admin'=>$_SESSION['admin'],'csrf'=>$_SESSION['csrf']]);
 }
 if($action==='admin_session'){json_out(['ok'=>true,'admin'=>admin_session()]);}
 if($action==='admin_logout'){start_session('__Host-ha88_admin');$id=(int)($_SESSION['admin']['id']??0);$_SESSION=[];session_destroy();if($id)audit($id,'ADMIN_LOGOUT','AUTH');json_out(['ok'=>true]);}
 if($action==='register'){
  require_post();$b=body();$u=trim((string)($b['username']??''));$email=trim((string)($b['email']??''));$pw=(string)($b['password']??'');$cn=trim((string)($b['character_name']??$u));
  if(!preg_match('/^[A-Za-z0-9_]{3,40}$/',$u)||strlen($pw)<8||strlen($cn)<2||strlen($cn)>60)json_out(['error'=>'invalid_input'],422);
  $pdo=db();$pdo->beginTransaction();try{$s=$pdo->prepare('INSERT INTO players(username,email,password_hash,character_name) VALUES(?,?,?,?) RETURNING id');$s->execute([$u,$email!==''?$email:null,password_hash($pw,PASSWORD_ARGON2ID),$cn]);$id=(int)$s->fetchColumn();$pdo->prepare('INSERT INTO player_wallets(player_id,balance) VALUES(?,1000000)')->execute([$id]);$pdo->prepare("INSERT INTO wallet_ledger(player_id,amount,balance_after,type,reference_id,reason) VALUES(?,1000000,1000000,'welcome_test',NULL,'TEST starting balance')")->execute([$id]);$pdo->commit();issue_player_session($id);json_out(['ok'=>true,'player'=>['id'=>$id,'username'=>$u],'balance'=>1000000,'mode'=>'TEST']);}catch(PDOException $e){$pdo->rollBack();if($e->getCode()==='23505')json_out(['error'=>'username_or_email_exists'],409);throw $e;}
 }
 if($action==='login'){
  require_post();$b=body();$u=trim((string)($b['username']??''));$pw=(string)($b['password']??'');$s=db()->prepare("SELECT p.id,p.username,p.password_hash,p.status,p.character_name,w.balance FROM players p JOIN player_wallets w ON w.player_id=p.id WHERE p.username=? LIMIT 1");$s->execute([$u]);$r=$s->fetch();if(!$r||$r['status']!=='active'||!password_verify($pw,(string)$r['password_hash']))json_out(['error'=>'invalid_credentials'],401);issue_player_session((int)$r['id']);db()->prepare('UPDATE players SET last_login_at=now() WHERE id=?')->execute([(int)$r['id']]);json_out(['ok'=>true,'player'=>['id'=>(int)$r['id'],'username'=>$r['username'],'character_name'=>$r['character_name']],'balance'=>(float)$r['balance'],'mode'=>'TEST']);
 }
 if($action==='logout'){start_session('__Host-ha88_player');$_SESSION=[];session_destroy();json_out(['ok'=>true]);}
 if($action==='session'){$p=player_session();if(!$p)json_out(['ok'=>true,'authenticated'=>false]);$s=db()->prepare('SELECT p.id,p.username,p.character_name,p.status,w.balance FROM players p JOIN player_wallets w ON w.player_id=p.id WHERE p.id=?');$s->execute([(int)$p['id']]);$r=$s->fetch();if(!$r)json_out(['ok'=>true,'authenticated'=>false]);json_out(['ok'=>true,'authenticated'=>true,'player'=>$r,'mode'=>'TEST']);}
 if($action==='wallet'){$p=require_player();$q=db()->prepare('SELECT id,amount,balance_after,type,reference_id,reason,created_at FROM wallet_ledger WHERE player_id=? ORDER BY id DESC LIMIT 50');$q->execute([(int)$p['id']]);json_out(['ok'=>true,'balance'=>wallet_balance((int)$p['id']),'ledger'=>$q->fetchAll(),'mode'=>'TEST']);}
 if($action==='game_list'){ $out=[];foreach(registry() as $g)$out[]=game_cfg($g['code']);json_out(['ok'=>true,'games'=>$out,'mode'=>'TEST']);}
 if($action==='game_config'){$c=trim((string)($_GET['game']??''));if(!valid_game($c))json_out(['error'=>'unknown_game'],404);json_out(['ok'=>true,'game'=>game_cfg($c)]);}
 if($action==='game_round'){$c=trim((string)($_GET['game']??''));if(!valid_game($c))json_out(['error'=>'unknown_game'],404);$r=new_round($c);json_out(['ok'=>true,'game'=>game_cfg($c),'round'=>$r,'mode'=>'TEST']);}
 if($action==='place_bet'){
  require_post();$p=require_player();$b=body();$game=trim((string)($b['game_code']??''));$rid=trim((string)($b['round_id']??''));$code=trim((string)($b['bet_code']??''));$amt=(float)($b['amount']??0);if(!valid_game($game)||$rid===''||$code===''||$amt<=0)json_out(['error'=>'invalid_input'],422);$cfg=game_cfg($game);if($amt<(float)($cfg['min_bet'])||((float)$cfg['max_bet']>0&&$amt>(float)$cfg['max_bet']))json_out(['error'=>'bet_limit'],422);
  $pdo=db();$pdo->beginTransaction();try{$q=$pdo->prepare("SELECT * FROM game_rounds WHERE game_code=? AND round_id=? AND status='open' AND closes_at>now() FOR UPDATE");$q->execute([$game,$rid]);if(!$q->fetch())throw new RuntimeException('round_closed');$bal=(float)$pdo->query('SELECT balance FROM player_wallets WHERE player_id='.(int)$p['id'].' FOR UPDATE')->fetchColumn();if($bal<$amt)throw new RuntimeException('insufficient_balance');$nb=$bal-$amt;$pdo->prepare('UPDATE player_wallets SET balance=?,version=version+1,updated_at=now() WHERE player_id=?')->execute([$nb,(int)$p['id']]);$ins=$pdo->prepare('INSERT INTO bets(player_id,game_code,round_id,bet_code,amount) VALUES(?,?,?,?,?) RETURNING id');$ins->execute([(int)$p['id'],$game,$rid,$code,$amt]);$bid=$ins->fetchColumn();$pdo->prepare("INSERT INTO wallet_ledger(player_id,amount,balance_after,type,reference_id,reason) VALUES(?,?,?,?,?,?)")->execute([(int)$p['id'],-$amt,''.$nb,'bet',(string)$bid,'TEST game bet']);$pdo->commit();json_out(['ok'=>true,'bet_id'=>$bid,'balance'=>$nb,'mode'=>'TEST']);}catch(Throwable $e){$pdo->rollBack();$m=$e->getMessage();$code2=in_array($m,['insufficient_balance','round_closed'],true)?409:422;json_out(['error'=>$m],$code2);}
 }
 if($action==='settle_round'){$game=trim((string)($_GET['game']??''));$rid=trim((string)($_GET['round']??''));if(!valid_game($game)||$rid==='')json_out(['error'=>'invalid_input'],422);$r=settle_round($game,$rid);json_out(['ok'=>true,'round'=>$r,'mode'=>'TEST']);}

 $a=require_admin();$pdo=db();
 if($action==='admin_csrf'){json_out(['ok'=>true,'csrf'=>csrf_token()]);}
 if($action==='admin_overview'){$players=(int)$pdo->query('SELECT count(*) FROM players')->fetchColumn();$rounds=(int)$pdo->query('SELECT count(*) FROM game_rounds')->fetchColumn();$audits=(int)$pdo->query('SELECT count(*) FROM admin_audit_log')->fetchColumn();json_out(['ok'=>true,'overview'=>['players'=>$players,'rounds'=>$rounds,'audit_events'=>$audits,'games'=>count(registry()),'mode'=>'TEST']]);}
 if($action==='admin_games'){$rows=[];foreach(registry() as $g)$rows[]=game_cfg($g['code']);json_out(['ok'=>true,'games'=>$rows]);}
 if($action==='admin_game_update'){require_post();require_csrf();require_role($a,['super_admin']);$b=body();$game=trim((string)($b['game_code']??''));$en=filter_var($b['enabled']??true,FILTER_VALIDATE_BOOLEAN,FILTER_NULL_ON_FAILURE);$min=(float)($b['min_bet']??0);$max=(float)($b['max_bet']??0);$sec=max(5,min(3600,(int)($b['round_seconds']??30)));$dif=(string)($b['difficulty']??'Normal');if(!valid_game($game)||$en===null||$min<0||$max<0||($max>0&&$max<$min)||!in_array($dif,['Easy','Normal','Hard','Extreme'],true))json_out(['error'=>'invalid_input'],422);$old=game_cfg($game);$q=$pdo->prepare('INSERT INTO game_admin_config(game_code,enabled,min_bet,max_bet,round_seconds,difficulty,updated_by) VALUES(?,?,?,?,?,?,?) ON CONFLICT(game_code) DO UPDATE SET enabled=EXCLUDED.enabled,min_bet=EXCLUDED.min_bet,max_bet=EXCLUDED.max_bet,round_seconds=EXCLUDED.round_seconds,difficulty=EXCLUDED.difficulty,updated_by=EXCLUDED.updated_by,updated_at=now()');$q->execute([$game,$en,$min,$max,$sec,$dif,(int)$a['id']]);audit((int)$a['id'],'GAME_CONFIG_UPDATE','GAME',$game,$old,compact('en','min','max','sec','dif'),(string)($b['reason']??''));json_out(['ok'=>true,'game'=>game_cfg($game)]);}
 if($action==='admin_round_result'){require_post();require_csrf();require_role($a,['super_admin']);$b=body();$game=trim((string)($b['game_code']??''));$rid=trim((string)($b['round_id']??''));$result=trim((string)($b['result_code']??''));if(!valid_game($game)||$rid===''||$result==='')json_out(['error'=>'invalid_input'],422);$q=$pdo->prepare('INSERT INTO game_test_round_controls(game_code,round_id,result_code,created_by) VALUES(?,?,?,?) ON CONFLICT(game_code,round_id) DO UPDATE SET result_code=EXCLUDED.result_code,created_by=EXCLUDED.created_by,created_at=now()');$q->execute([$game,$rid,$result,(int)$a['id']]);audit((int)$a['id'],'ROUND_TEST_RESULT','GAME_ROUND',$game.'|'.$rid,null,['result_code'=>$result],(string)($b['reason']??''));json_out(['ok'=>true,'scope'=>'game_round']);}
 if($action==='admin_wallet_test'){require_post();require_csrf();require_role($a,['super_admin']);$b=body();$pid=(int)($b['player_id']??0);$amt=(float)($b['amount']??0);$dir=(string)($b['direction']??'');$reason=trim((string)($b['reason']??''));if($pid<=0||$amt<=0||!in_array($dir,['credit','debit'],true)||$reason==='')json_out(['error'=>'invalid_input'],422);$new=ledger($pid,$dir==='credit'?$amt:-$amt,'admin_test',(string)$a['id'],$reason);$q=$pdo->prepare('INSERT INTO admin_test_wallet_ops(admin_id,player_id,amount,direction,reason) VALUES(?,?,?,?,?) RETURNING id');$q->execute([(int)$a['id'],$pid,$amt,$dir,$reason]);$id=$q->fetchColumn();audit((int)$a['id'],'TEST_WALLET_ADJUST','PLAYER',(string)$pid,null,['amount'=>$amt,'direction'=>$dir,'balance_after'=>$new],$reason);json_out(['ok'=>true,'operation_id'=>$id,'balance'=>$new,'mode'=>'TEST']);}
 if($action==='admin_players'){$limit=min(100,max(1,(int)($_GET['limit']??50)));$offset=max(0,(int)($_GET['offset']??0));$q=$pdo->prepare('SELECT p.id,p.username,p.email,p.character_name,p.status,p.created_at,p.last_login_at,w.balance FROM players p JOIN player_wallets w ON w.player_id=p.id ORDER BY p.id DESC LIMIT ? OFFSET ?');$q->bindValue(1,$limit,PDO::PARAM_INT);$q->bindValue(2,$offset,PDO::PARAM_INT);$q->execute();json_out(['ok'=>true,'players'=>$q->fetchAll(),'limit'=>$limit,'offset'=>$offset]);}
 if($action==='admin_player_status'){require_post();require_csrf();require_role($a,['super_admin','emergency_admin']);$b=body();$pid=(int)($b['player_id']??0);$st=(string)($b['status']??'');if($pid<=0||!in_array($st,['active','suspended','banned'],true))json_out(['error'=>'invalid_input'],422);$q=$pdo->prepare('UPDATE players SET status=? WHERE id=? RETURNING id,status');$q->execute([$st,$pid]);$r=$q->fetch();if(!$r)json_out(['error'=>'player_not_found'],404);audit((int)$a['id'],'PLAYER_STATUS','PLAYER',(string)$pid,null,$r,(string)($b['reason']??''));json_out(['ok'=>true,'player'=>$r]);}
 if($action==='admin_transactions'){$rows=$pdo->query('SELECT id,player_id,amount,direction,reason,created_at FROM admin_test_wallet_ops ORDER BY id DESC LIMIT 200')->fetchAll();json_out(['ok'=>true,'transactions'=>$rows]);}
 if($action==='admin_audit'){$limit=min(200,max(1,(int)($_GET['limit']??50)));$q=$pdo->prepare('SELECT id,admin_id,action,scope,target_id,reason,created_at FROM admin_audit_log ORDER BY id DESC LIMIT ?');$q->bindValue(1,$limit,PDO::PARAM_INT);$q->execute();json_out(['ok'=>true,'audit'=>$q->fetchAll()]);}
 if($action==='admin_support'){require_post();require_csrf();$b=body();$pid=(int)($b['player_id']??0);$subject=trim((string)($b['subject']??'Support'));$msg=trim((string)($b['message']??''));$status=(string)($b['status']??'open');if(!$msg||!in_array($status,['open','pending','resolved'],true))json_out(['error'=>'invalid_input'],422);$q=$pdo->prepare('INSERT INTO support_tickets(player_id,status,subject) VALUES(?,?,?) RETURNING id');$q->execute([$pid?:null,$status,$subject]);$tid=$q->fetchColumn();$pdo->prepare("INSERT INTO support_messages(ticket_id,sender_type,sender_id,message) VALUES(?,'admin',?,?)")->execute([$tid,(int)$a['id'],$msg]);audit((int)$a['id'],'SUPPORT_MESSAGE','TICKET',(string)$tid,null,['status'=>$status],null);json_out(['ok'=>true,'ticket_id'=>$tid]);}
 if($action==='admin_create'){require_post();require_csrf();require_role($a,['super_admin']);$b=body();$u=trim((string)($b['username']??''));$pw=(string)($b['password']??'');$role=(string)($b['role']??'admin');$otp=trim((string)($b['totp_secret']??''));if(!preg_match('/^[A-Za-z0-9_.-]{3,80}$/',$u)||strlen($pw)<12||!in_array($role,['admin','super_admin','emergency_admin'],true)||$otp==='')json_out(['error'=>'invalid_input'],422);$q=$pdo->prepare('INSERT INTO admin_accounts(username,password_hash,role,totp_secret_enc) VALUES(?,?,?,?) RETURNING id,username,role');$q->execute([$u,password_hash($pw,PASSWORD_ARGON2ID),$role,encrypt_secret($otp)]);$r=$q->fetch();audit((int)$a['id'],'ADMIN_CREATE','ADMIN',(string)$r['id'],null,$r);json_out(['ok'=>true,'admin'=>$r]);}
 if($action==='admin_list_accounts'){require_role($a,['super_admin']);$rows=$pdo->query('SELECT id,username,role,active,created_at,last_login_at FROM admin_accounts ORDER BY id')->fetchAll();json_out(['ok'=>true,'admins'=>$rows]);}
 if($action==='admin_set_active'){require_post();require_csrf();require_role($a,['super_admin']);$b=body();$id=(int)($b['admin_id']??0);$active=(bool)($b['active']??false);if($id<=0||$id===(int)$a['id'])json_out(['error'=>'invalid_target'],422);$q=$pdo->prepare('UPDATE admin_accounts SET active=? WHERE id=?');$q->execute([$active,$id]);audit((int)$a['id'],'ADMIN_STATUS','ADMIN',(string)$id,null,['active'=>$active]);json_out(['ok'=>true]);}
 json_out(['error'=>'unknown_action'],404);
}catch(Throwable $e){error_log((string)$e);json_out(['error'=>'server_error'],500);}
